### ISSUE TITLE
EU legal's PDF invoice doesn't match PrestaShop's redesigned generating process any longer

### ISSUE THREAD

**Issue by Nobodaddy** [EU-Legal/modules-1.6.0.14#13]
For some reason I don't know the pdf invoice plus the generating process was deeply changed some days ago. It is prior understatement to comment this as just '// Better alignments'! 
These modifications affect not only the invoice tpl files but also several order and pdf classes. The now 10 files that are merged into pdf invoice show new variables, too (e.g. in invoice.tax-tab.tpl), and new styles assembled in a pseudo css file called  invoice.style-tab.tpl.
Obviously there must be even more more changes because in my first tests this new invoice did not work properly though there were no error messages. My complaints were refused and a pull request in this regard was meantime closed.
However, I guess there are some more serious changes necessary in EU legal to make it work properly for 1.6.0.14 or the forthcoming 1.6.1. 
Good luck, guys!

**Comment by gurkcity** [comment]
Thanks for this hint. We will see and work on this at the moment the new version will be released.
