### ISSUE TITLE
moneybookers 

### ISSUE THREAD

**Issue by Chrisi1321** [EU-Legal/modules-1.6.0.14#18]
Warum auch immer, bekomme ich seit der 1.6.0.14 Moneybookers im Warenkorb nicht mehr angezeigt.
Da das Modul nicht mehr im Modul integriert ist, habe ich mir die Version 1.6.9 direkt von PS geladen. Anscheinend sind die Hooks da ja aber vorhanden.

Aktiviert ist es bei den Zahlungsarten.

**Comment by gurkcity** [comment]
komplett reset den Moneybookers Moduls versucht?

**Comment by Chrisi1321** [comment]
Ich habe das Poblem hierhin verlagert : http://forge.prestashop.com/browse/PNM-3484
