### ISSUE TITLE
Updateprobleme - hat jemand einen Tipp?

### ISSUE THREAD

**Issue by telefonino** [EU-Legal/modules-1.6.0.14#19]
The following module(s) could not be installed properly:

    eu_legal :
        The method getTaxesRate in the class Carrier is already overriden.
        The method getProducts in the class Cart is already overriden.
        The method getProducts in the class Category is already overriden.
        The method getContentFromId in the class CMS is already overriden.
        The method Send in the class Mail is already overriden.
        The method getProducts in the class Manufacturer is already overriden.
        The method getModulesOnDisk in the class Module is already overriden.
        The method __construct in the class Order is already overriden.
        The method validateOrder in the class PaymentModule is already overriden.
        The method getTaxTabContent in the class HTMLTemplateInvoice is already overriden.
        The method getTaxTabContent in the class HTMLTemplateOrderSlip is already overriden.
        The method __construct in the class Product is already overriden.
        The method getBestSales in the class ProductSale is already overriden.
        The method getProducts in the class Supplier is already overriden.
        The method getTaxData in the class TaxCalculator is already overriden.
        The method initFormInformations in the class AdminProductsController is already overriden.
        The method sendConfirmationMail in the class AuthController is already overriden.
        The method initContent in the class OrderController is already overriden.
        The method initContent in the class OrderDetailController is already overriden.
        The method init in the class OrderOpcController is already overriden.
        The method __construct in the class ParentOrderController is already overriden.
        The method initContent in the class ProductController is already overriden.

**Comment by gurkcity** [comment]
original Overrides wiederherstellen, dann nochmal probieren
