### ISSUE TITLE
inkl. MwSt

### ISSUE THREAD

**Issue by ZoXx** [EU-Legal/modules-1.6.0.14#3]
Wird doppelt angezeigt.

**Comment by gurkcity** [comment]
Das haben wir den Entwicklern des PrestaShop-Themes zu verdanken.
Einfach in der product.tpl nach tax suchen und dann den Bereich am besten ausklammern.
In EU Legal haben wir noch keinen Fix dafür.

**Comment by ZoXx** [comment]
Sorry gerade erst gesehen !
Danke schonmal !
Die Zeilen habe ich gefunden, aber wie genau Klammere ich diese auch?
Habe es mit sämtlichen Sachen probiert, kannst du mir bitte kurz unter die Arme greifen?
Danke!

**Comment by gurkcity** [comment]
Suche in der product.tpl nach tax, dann spielen wir dies hier statt dem dort stehenden Code ein: 
										<span class="tax-shipping-info eu-legal">
											<span class="tax_info">
												{if $tax_enabled  && ((isset($display_tax_label) && $display_tax_label == 1) || !isset($display_tax_label))}
													{if $priceDisplay == 1}{l s='tax excl.'}{else}{l s='tax incl.'}{/if}
												{/if}
											</span>
										</span>
