### ISSUE TITLE
keine Bestellungen mehr, nur noch verwaiste Warenkörbe, Warenkörbe nicht mehr anzeigbar

### ISSUE THREAD

**Issue by kullii** [EU-Legal/modules-1.6.0.14#5]
zuerst war es nur in einem Shop

mittlerweile auch in einem gut frequentierten Live-Shop: dort gibt es nun nur noch verwaiste Warenkörbe und keine Bestellungen mehr;
geändert wurde an den beiden Live-Shops gar nichts

allen gemein ist Eu-legal
prestashop sagt es liegt an deren Overrides

folgendes kommt wenn man die verwaisten Warenkörbe aufrufen will:
[PrestaShopException]

Invalid address #56
at line 362 in file classes/Address.php

357. 		if ($id_address)
358. 		{
359. 			$address = new Address((int)$id_address);
360. 
361. 			if (!Validate::isLoadedObject($address))
362. 				throw new PrestaShopException('Invalid address #'.(int)$id_address);
363. 		}
364. 		elseif ($with_geoloc && isset($context->customer->geoloc_id_country))
365. 		{
366. 			$address = new Address();
367. 			$address->id_country = (int)$context->customer->geoloc_id_country;

    AddressCore::initialize - [line 702 - override/classes/Cart.php] - [1 Arguments]

    697. 		$context = Context::getContext();
    698. 
    699. 		if (Configuration::get('PS_TAX_ADDRESS_TYPE') == 'id_address_invoice')
    700. 			$address = Address::initialize((int)$this->id_address_invoice);
    701. 		else
    702. 			$address = Address::initialize((int)$this->id_address_delivery);
    703. 
    704. 		if (!count($products))
    705. 			return false;
    706. 
    707. 		$prepared_taxes = array();

    Cart->getTaxDetails - [line 338 - override/classes/Cart.php]

    333. 			Cart::ONLY_WRAPPING,
    334. 			Cart::ONLY_PRODUCTS_WITHOUT_SHIPPING,
    335. 			Cart::ONLY_PHYSICAL_PRODUCTS_WITHOUT_SHIPPING,
    336. 		);
    337. 
    338. 		$taxes = $this->getTaxDetails();
    339. 		$order_total_products_taxed = 0;
    340. 
    341. 		// Define virtual context to prevent case where the cart is not the in the global context
    342. 		$virtual_context = Context::getContext()->cloneContext();
    343. 		$virtual_context->cart = $this;

    Cart->getOrderTotal - [line 1292 - classes/Cart.php] - [2 Arguments]

    1287. 		$cart = new Cart($id_cart);
    1288. 		if (!Validate::isLoadedObject($cart))
    1289. 			die(Tools::displayError());
    1290. 
    1291. 		$with_taxes = $use_tax_display ? $cart->_taxCalculationMethod != PS_TAX_EXC : true;
    1292. 		return Tools::displayPrice($cart->getOrderTotal($with_taxes, $type), Currency::getCurrencyInstance((int)$cart->id_currency), false);
    1293. 	}
    1294. 
    1295. 
    1296. 	public static function getOrderTotalUsingTaxCalculationMethod($id_cart)
    1297. 	{

    CartCore::getTotalCart - [line 830 - controllers/admin/AdminCartsController.php] - [3 Arguments]

    825. 	{
    826. 		$context = Context::getContext();
    827. 		$context->cart = new Cart($id_cart);
    828. 		$context->currency = new Currency((int)$context->cart->id_currency);
    829. 		$context->customer = new Customer((int)$context->cart->id_customer);
    830. 		return Cart::getTotalCart($id_cart, true, Cart::BOTH_WITHOUT_SHIPPING);
    831. 	}
    832. 
    833. 	public static function replaceZeroByShopName($echo, $tr)
    834. 	{
    835. 		return ($echo == '0' ? Configuration::get('PS_SHOP_NAME') : $echo);

    AdminCartsControllerCore->getOrderTotalUsingTaxCalculationMethod - [line - ] - [2 Arguments]
    call_user_func_array - [line 321 - classes/helper/HelperList.php] - [2 Arguments]
    HelperListCore->displayListContent - [line 150 - classes/helper/HelperList.php]

    145. 		$this->orderBy = preg_replace('/^([a-z _]*!)/Ui', '', $this->orderBy);
    146. 		$this->orderWay = preg_replace('/^([a-z _]*!)/Ui', '', $this->orderWay);
    147. 
    148. 		$this->tpl->assign(array(
    149. 			'header' => $this->displayListHeader(), // Display list header (filtering, pagination and column names)
    150. 			'content' => $this->displayListContent(), // Show the content of the table
    151. 			'footer' => $this->displayListFooter() // Close list table and submit button
    152. 		));
    153. 		return parent::generate();
    154. 	}
    155. 

    HelperListCore->generateList - [line 885 - controllers/admin/AdminCartsController.php] - [2 Arguments]
    AdminCartsControllerCore->renderList - [line 1848 - classes/controller/AdminController.php]

    1843. 
    1844. 		elseif (!$this->ajax)
    1845. 		{
    1846. 			$this->content .= $this->renderModulesList();
    1847. 			$this->content .= $this->renderKpis();
    1848. 			$this->content .= $this->renderList();
    1849. 			$this->content .= $this->renderOptions();
    1850. 
    1851. 			// if we have to display the required fields form
    1852. 			if ($this->required_database)
    1853. 				$this->content .= $this->displayRequiredFields();

    AdminControllerCore->initContent - [line 180 - classes/controller/Controller.php]

    175. 
    176. 			if (!$this->content_only && ($this->display_header || (isset($this->className) && $this->className)))
    177. 				$this->initHeader();
    178. 
    179. 			if ($this->viewAccess())
    180. 				$this->initContent();
    181. 			else
    182. 				$this->errors[] = Tools::displayError('Access denied.');
    183. 
    184. 			if (!$this->content_only && ($this->display_footer || (isset($this->className) && $this->className)))
    185. 				$this->initFooter();

    ControllerCore->run - [line 39 - override/classes/controller/Controller.php]

    34.     	$name_module = 'cachesite';
    35.     	$page_name = Dispatcher::getInstance()->getController();
    36.     	$cachesite = (int)Configuration::get($name_module.'cache_on');
    37.     	$is_page_cache_on = (int)Configuration::get($name_module.$page_name.'_on');
    38.     	if(!Module::isInstalled('cachesite') || !Module::isEnabled('cachesite') || $cachesite == 0 || $is_page_cache_on == 0) {
    39.             return parent::run();
    40.         }
    41.         
    42.         $is_stat_on = (int)Configuration::get($name_module.'stat_on');
    43.         if($is_stat_on) {
    44.             $then = microtime(true);

    Controller->run - [line 373 - classes/Dispatcher.php]

    368. 			// Execute hook dispatcher
    369. 			if (isset($params_hook_action_dispatcher))
    370. 				Hook::exec('actionDispatcher', $params_hook_action_dispatcher);
    371. 
    372. 			// Running controller
    373. 			$controller->run();
    374. 		}
    375. 		catch (PrestaShopException $e)
    376. 		{
    377. 			$e->displayMessage();
    378. 		}

    DispatcherCore->dispatch - [line 54 - admin/index.php]

    49. 	$_POST['controller'] = strtolower($_POST['tab']);
    50. if (!isset($_REQUEST['controller']) && isset($_REQUEST['tab']))
    51. 	$_REQUEST['controller'] = strtolower($_REQUEST['tab']);
    52. 
    53. // Prepare and trigger admin dispatcher
    54. Dispatcher::getInstance()->dispatch();

**Comment by kullii** [comment]
EU-Legal override/classes/cart.php

irgenwas mit den virtuellen Produkten

ich hab den Bereich ausgeklammert, jetzt kann ich die verwaisten Warenkörbe wieder ansehen

**Comment by kullii** [comment]
sehe ich das richtig, dass der override cart.php noch von 1.6.0.9 ist ?

**Comment by gurkcity** [comment]
nein, die Cart.php Override wurde an die neueste Version 1.6.0.14 angepasst.

Wurden evtl. Adressen gelöscht? Ich vermute einen Bug in PrestaShop.
